### ISSUE TITLE
ImportError: cannot import name 'backend' from 'probnum'

### ISSUE THREAD

**Issue by Fangwq** [JonathanWenger/itergp#1]
I install the package `probnum 0.1.19`,  and run the code, 
```
import sys
sys.path.append("./itergp-main/src")
from itergp import datasets

data = datasets.uci.BikeSharing(dir="data/uci")
print(data.train.y)
``` 
but, an error occurs:
```
ImportError: cannot import name 'backend' from 'probnum'
```
What's the problem here?

**Comment by JonathanWenger** [comment]
Make sure you don't install ProbNum first, since currently IterGP depends on a yet-to-be-merged feature of ProbNum. Uninstall ProbNum in your environment and reinstall IterGP. It will then automatically install the right ProbNum version via its dependencies.
