### ISSUE TITLE
Problems with importing itergp: module named 'fcntl' not found

### ISSUE THREAD

**Issue by L-in-da** [JonathanWenger/itergp#4]
I've tried to import itergp, as stated in the README file, but got the error:
ModuleNotFoundError: No module named 'fcntl' 
It seems as the fcntl module is not available on Windows. So is it nevertheless possible to import itergp on a windows pc?

**Comment by JonathanWenger** [comment]
Hi @L-in-da. We unfortunately just realized the issue you describe. The package [KeOPs](https://www.kernel-operations.io/keops/index.html) that IterGP depends on does not have Windows support yet (see also https://github.com/getkeops/keops/issues/43).  KeOps enables large-scale matrix-vector multiplies with a kernel matrix. 

We are working on a solution for the homework currently. For now if you have a team member with a mac or linux machine try using that.

**Comment by JonathanWenger** [comment]
I just implemented a hotfix, that avoids the use of KeOps on Windows. This means on Windows you may not be able to scale to very large kernel matrices (n > 10000), since the implementation uses dense matrices. That should not be an issue for the homework however.
